[package]
name = "trexd"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "^0.1"
pingora = { version = "^0.6", features = ["proxy", "openssl"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
log = "^0.4"
pretty_env_logger = "^0.4"
http = "^1.3"
