name: release binary

on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: setup
        run: |
          sudo apt update
          sudo apt install -y gcc-aarch64-linux-gnu
          rustup target add aarch64-unknown-linux-gnu
          echo -e "[target.aarch64-unknown-linux-gnu]\nlinker = \"aarch64-linux-gnu-gcc\"" > ~/.cargo/config
      - name: build
        run: |
          cargo build --target aarch64-unknown-linux-gnu --release
          cp target/aarch64-unknown-linux-gnu/release/trexd trexd-aarch64-unknown-linux-gnu
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: trexd-aarch64-unknown-linux-gnu
          path: trexd-aarch64-unknown-linux-gnu

